name: packager
on:
  push:
    tags:
      - '*-release[0-9]*'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      # setup under repo > settings > secrets

    steps:
      - name: Clone project
        uses: actions/checkout@main

      - name: Package and release
        uses: BigWigsMods/packager@v2

